version: '3.9'
services:
  db:
    image: postgres:16
    container_name: todo_pg
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  pg_data: