version: '3.9'
services:
  db:
    image: postgres:16
    container_name: todo_pg
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: todo_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=tododb;Username=todo;Password=todo
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: todo_web
    ports:
      - "8081:80"
    depends_on:
      api:
        condition: service_started
volumes:
  pg_data:
